### PR TITLE
[doc] Aktualisierung für 2.2.2.3.

### PR DESCRIPTION
**Pull request by computersalat**
openSUSE Leap 15.x und SUSE Linux Enterprise Server 15 GA

### CODE REVIEW

**Review by mbunkus — CHANGES_REQUESTED** [review]
Thanks, but you reformatted all of the XML file to match your own line wrapping settings, making it next to impossible to track what you actually changed besides white spaces. Please recreate the change without messing up everything else in the XML. Thanks.

**Comment by computersalat** [comment]
> Thanks, but you reformatted all of the XML file to match your own line wrapping settings, making it next to impossible to track what you actually changed besides white spaces. Please recreate the change without messing up everything else in the XML. Thanks.

I didn't reformat the whole XML, but [XMLmind](http://www.xmlmind.com/xmleditor/_download/xxe-perso-10_0_0.zip) decided to do so. Obviously it is not using same settings as you do.
Maybe it would be helpful to have same settings ? Is there something like that ?

**Comment by mbunkus** [comment]
We don't have a canonical tool to edit XML files. We use whichever editor we usually use, I guess — for me that's Emacs, for Jan I guess vim. Those don't auto-reformat everything.

I cannot help you with XMLmind (or any other XML editor). If the changes you're trying to make are small, try using a plain text editor instead of something XML-centric.

**Comment by computersalat** [comment]
> We don't have a canonical tool to edit XML files. We use whichever editor we usually use, I guess — for me that's Emacs, for Jan I guess vim. Those don't auto-reformat everything.
> 
> I cannot help you with XMLmind (or any other XML editor). If the changes you're trying to make are small, try using a plain text editor instead of something XML-centric.

OK ... I understand. Will rework my PR
But why are you telling people to make use of it (see kivitendo documentation) when you don't use it yourself ?
```
4.8. Dokumentation erstellen
4.8.1. Einführung
Diese Dokumentation ist in DocBook™ XML geschrieben. Zum Bearbeiten reicht grundsätzlich ein Text-Editor. Mehr Kom-
fort bekommt man, wenn man einen dedizierten XML-fähigen Editor nutzt, der spezielle Unterstützung für DocBook™ mit-
bringt. Wir empfehlen dafür den XMLmind XML Editor5, der bei nicht kommerzieller Nutzung kostenlos ist.
```

**Comment by computersalat** [comment]
@mbunkus 
would you please so kind and review it again.
Thank you

**Review by mbunkus — APPROVED** [review]
Looks good to me now. Thanks.

**Comment by computersalat** [comment]
> Looks good to me now. Thanks.

@mbunkus 
Any attempt to merge ?

**Comment by computersalat** [comment]
@mbunkus 
is this obsolete now as of the many conflicts now ?

**Comment by computersalat** [comment]
@mbunkus 
Did rebase to current master.
Is it now worth to be merged ?
Thank you

**Comment by mbunkus** [comment]
Thanks, and sorry for forgetting about it for so long.

**Pull request merged**
